version: '3.8'


services:
  collector:
    build:
      context: ./data/collector
      dockerfile: Dockerfile
    container_name: spatially_collector
    stdin_open: true  # Keep stdin open (docker run -i)
    tty: true         # Allocate a pseudo-TTY (docker run -t)
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/ac215-spatially-data-accessor-keys.json
    volumes:
      - ./data/downloads:/app/data/downloads # This will mount our ./data/downloads as /app/data/downloads in the container
      - ./secrets:/secrets:ro # This will mount our ./secrets as /secrets in the container
      - ./data/collector:/app # This will mount our ./data/collector as /app in the container

  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio_development_plans 
    ports:
      - "8080:8080"
      # To the label-studio frontend the host for accessing the label studio backend will be
      # http://label-studio-ml-backend:9090
    env_file:
      - ./secrets/spatially-aws-postgres-db.env
      - ./secrets/spatially-labelstudio-db.env
      - ./secrets/spatially-gcp-bucket.env
    environment:
      # PostgreSQL Database Configuration
      - DJANGO_DB=default
      # Local file serving for PDFs (for fallback, not used with GCS)
      # - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      # - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
      # Google Cloud Storage Configuration
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/ac215-spatially-data-accessor-keys.json
    volumes:
      - ./data/downloads/development_plans:/label-studio/files:ro
      - development_plans_label_studio_data:/label-studio/data
      - ./secrets:/secrets:ro
    networks:
      - development_plans_label_studio_network
    command: label-studio --host 0.0.0.0
  

  label-studio-ml-backend:
    container_name: label-studio-ml-backend
    build:
      context: ./label_studio/label_studio_development_plans_backend
      dockerfile: Dockerfile
    init: true
    # build:
    #   context: ./label_studio/label-studio-ml-backend/label_studio_ml/examples/huggingface_ner
    #   args:
    #     TEST_ENV: ${TEST_ENV}
    environment:
      # If you are using this model for training, you have to connect it to Label Studio
      - LABEL_STUDIO_HOST=http://label-studio:8080
      - LABEL_STUDIO_API_KEY=your-api-key
      # Use any model for [AutoModelForSequenceClassification](https://huggingface.co/transformers/v3.0.2/model_doc/auto.html#automodelforsequenceclassification)
      - BASELINE_MODEL_NAME=nlpaueb/legal-bert-base-uncased
      # change it to this model if you want to run training
      # - BASELINE_MODEL_NAME=distilbert/distilbert-base-uncased
      # The model directory for the fine-tuned checkpoints (relative to $MODEL_DIR)
      - FINETUNED_MODEL_NAME=ner_model_for_development_plans
      # The number of labeled tasks to download from Label Studio before starting training
      - START_TRAINING_EACH_N_UPDATES=1
      # Learning rate
      - LEARNING_RATE=2e-5
      # Number of epochs
      - NUM_TRAIN_EPOCHS=3
      # Weight decay
      - WEIGHT_DECAY=0.01
      # specify these parameters if you want to use basic auth for the model server
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      # set the log level for the model server
      - LOG_LEVEL=DEBUG
      # any other parameters that you want to pass to the model server
      - ANY=PARAMETER
      # specify the number of workers and threads for the model server
      - WORKERS=1
      - THREADS=8
      # specify the model directory (likely you don't need to change this)
      - MODEL_DIR=/data/models
    ports:
      - "9090:9090"
    volumes:
      - "./label_studio/tmp/label_studio_development_plans_backend/server:/data"
      - "./label_studio/tmp/label_studio_development_plans_backend/.cache:/root/.cache"
    networks:
      - development_plans_label_studio_network

volumes:
  # This is a volume that is stored in the host machine (It is managed by Docker, not the user local machine)
  development_plans_label_studio_data:
    driver: local

networks:
  development_plans_label_studio_network:
    driver: bridge