"""
Census Processor for ingesting ACS data into the database.

This processor reads CSV files generated by the Census Collector and inserts
data into the following tables:
- CENSUS_TRACT: Geographic tracts
- ACS_TABLE: ACS table definitions
- ACS_VARIABLE: ACS variable definitions
- ACS_VALUE: Actual census values (with year)
"""

import os
import logging
import pandas as pd
from pathlib import Path
from typing import Dict, List, Optional
from io import StringIO
from psycopg2.extras import execute_values
from utils.db_accessor import DBAccessor
from utils.gcp_storage import GCPStorage
from template import BaseProcessor


class CensusProcessor(BaseProcessor):
    """Process census CSV files and ingest into database."""

    def __init__(self, city: str):
        super().__init__()
        self.city = city
        self._init_logger()
        self._init_db()
        self._init_storage()

    def _init_logger(self):
        """Initialize logger."""
        self.logger = logging.getLogger(f"{self.__class__.__name__}")
        if not self.logger.hasHandlers():
            handler = logging.StreamHandler()
            formatter = logging.Formatter("%(asctime)s %(levelname)s: %(message)s")
            handler.setFormatter(formatter)
            self.logger.addHandler(handler)
            self.logger.setLevel(logging.INFO)

    def _init_db(self):
        """Initialize database connection and create tables."""
        self.db_name = os.environ.get("APP_DB_NAME")
        self.db = DBAccessor(db_name=self.db_name)
        self._create_census_tables()

    def _init_storage(self):
        """Initialize GCP Storage client."""
        self.gcp_project = os.environ.get("GCP_PROJECT")
        self.gcp_bucket = os.environ.get("GCS_BUCKET_NAME")
        credentials_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
        self.storage = GCPStorage(
            gcp_project=self.gcp_project,
            bucket_name=self.gcp_bucket,
            credentials_path=credentials_path
        )

    def download_directory(self) -> str:
        """Return the download directory path for this processor."""
        return os.path.abspath(f"tmp/census/{self.city}")

    def gcp_storage_markdown_directory(self) -> str:
        """Return the GCS storage path for census CSV files."""
        return f"census/{self.city}"

    def _create_census_tables(self):
        """Create all census-related tables in the database."""
        self.logger.info("Creating census tables...")
        # Create topic enum type
        self.db.execute("""
            DO $$ BEGIN
                CREATE TYPE topic AS ENUM (
                    'DEMOGRAPHICS',
                    'HOUSEHOLD_COMPOSITION',
                    'HOUSING_STOCK',
                    'HOUSING_FINANCIALS',
                    'HOUSING_TENURE_OCCUPANCY',
                    'HOUSING_COST_BURDEN',
                    'HOUSING_AGE_CONDITION',
                    'VACANCY',
                    'INCOME',
                    'POVERTY',
                    'EMPLOYMENT',
                    'INDUSTRY',
                    'TRANSPORTATION',
                    'GEOGRAPHIC_MOBILITY',
                    'EDUCATION'
                );
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """)

        # Create ACS_TABLE table
        self.db.execute("""
            CREATE TABLE IF NOT EXISTS acs_table (
                acs_table_id VARCHAR(100) PRIMARY KEY,
                title TEXT,
                topic topic,
                table_type VARCHAR(200),
                description TEXT
            );
        """)

        # Create ACS_VARIABLE table
        self.db.execute("""
            CREATE TABLE IF NOT EXISTS acs_variable (
                id SERIAL PRIMARY KEY,
                acs_table_id VARCHAR(100) REFERENCES acs_table(acs_table_id),
                name TEXT,
                UNIQUE(acs_table_id, name)
            );
            CREATE INDEX IF NOT EXISTS idx_acs_variable_table ON acs_variable(acs_table_id);
        """)

        # Create ACS_VALUE table
        self.db.execute("""
            CREATE TABLE IF NOT EXISTS acs_value (
                acs_value_id SERIAL PRIMARY KEY,
                geoid VARCHAR(50) REFERENCES census_tracts(geoid),
                variable_id INTEGER REFERENCES acs_variable(id),
                year INTEGER NOT NULL,
                value FLOAT,
                ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(geoid, variable_id, year)
            );
            CREATE INDEX IF NOT EXISTS idx_acs_value_geoid ON acs_value(geoid);
            CREATE INDEX IF NOT EXISTS idx_acs_value_variable ON acs_value(variable_id);
            CREATE INDEX IF NOT EXISTS idx_acs_value_year ON acs_value(year);
        """)

        self.logger.info("Census tables created successfully")

    def _get_table_metadata(self, table_code: str) -> Dict:
        """
        Get metadata for an ACS table.

        Args:
            table_code: ACS table code (e.g., "DP04", "S1901")

        Returns:
            Dictionary with table metadata
        """
        # Map table codes to metadata
        # This is a simplified mapping - in production, you might fetch this from Census API
        table_metadata = {
            "DP02": {
                "title": "Selected Social Characteristics",
                "topic": "HOUSEHOLD_COMPOSITION",
                "table_type": "Data Profile",
                "description": "Social characteristics including household types, education, and language"
            },
            "DP04": {
                "title": "Selected Housing Characteristics",
                "topic": "HOUSING_STOCK",
                "table_type": "Data Profile",
                "description": "Housing characteristics including rent, tenure, and vacancy"
            },
            "DP05": {
                "title": "Demographic and Housing Estimates",
                "topic": "DEMOGRAPHICS",
                "table_type": "Data Profile",
                "description": "Population by age, race, and sex"
            },
            "S0701": {
                "title": "Geographic Mobility",
                "topic": "GEOGRAPHIC_MOBILITY",
                "table_type": "Subject Table",
                "description": "Migration patterns and geographic mobility"
            },
            "S0801": {
                "title": "Commuting Characteristics",
                "topic": "TRANSPORTATION",
                "table_type": "Subject Table",
                "description": "Commute to work patterns"
            },
            "S0802": {
                "title": "Means of Transportation to Work",
                "topic": "TRANSPORTATION",
                "table_type": "Subject Table",
                "description": "Vehicle availability and transportation modes"
            },
            "S0804": {
                "title": "Means of Transportation to Work by Selected Characteristics",
                "topic": "TRANSPORTATION",
                "table_type": "Subject Table",
                "description": "Detailed transportation mode characteristics"
            },
            "S1101": {
                "title": "Households and Families",
                "topic": "HOUSEHOLD_COMPOSITION",
                "table_type": "Subject Table",
                "description": "Household size and composition"
            },
            "S1501": {
                "title": "Educational Attainment",
                "topic": "EDUCATION",
                "table_type": "Subject Table",
                "description": "Education levels by demographics"
            },
            "S1701": {
                "title": "Poverty Status",
                "topic": "POVERTY",
                "table_type": "Subject Table",
                "description": "Poverty rates and thresholds"
            },
            "S1901": {
                "title": "Income in the Past 12 Months",
                "topic": "INCOME",
                "table_type": "Subject Table",
                "description": "Household income distribution"
            },
            "S1903": {
                "title": "Median Income",
                "topic": "INCOME",
                "table_type": "Subject Table",
                "description": "Median income by demographics"
            },
            "S2201": {
                "title": "Food Stamps/SNAP",
                "topic": "POVERTY",
                "table_type": "Subject Table",
                "description": "Food stamp and SNAP participation"
            },
            "S2301": {
                "title": "Employment Status",
                "topic": "EMPLOYMENT",
                "table_type": "Subject Table",
                "description": "Labor force participation and unemployment"
            },
            "S2403": {
                "title": "Industry by Sex",
                "topic": "INDUSTRY",
                "table_type": "Subject Table",
                "description": "Industry distribution by sex"
            },
            "S2404": {
                "title": "Industry by Sex for Full-Time Workers",
                "topic": "INDUSTRY",
                "table_type": "Subject Table",
                "description": "Full-time employment by industry"
            },
            "S2501": {
                "title": "Occupancy Characteristics",
                "topic": "HOUSING_TENURE_OCCUPANCY",
                "table_type": "Subject Table",
                "description": "Tenure and occupancy details"
            },
            "S2503": {
                "title": "Financial Characteristics",
                "topic": "HOUSING_FINANCIALS",
                "table_type": "Subject Table",
                "description": "Housing cost burden and mortgage status"
            },
        }

        return table_metadata.get(table_code, {
            "title": f"ACS Table {table_code}",
            "topic": "DEMOGRAPHICS",
            "table_type": "Unknown",
            "description": f"American Community Survey Table {table_code}"
        })

    def _ingest_acs_table(self, table_code: str):
        """
        Insert or update ACS table metadata.

        Args:
            table_code: ACS table code
        """
        metadata = self._get_table_metadata(table_code)

        self.db.execute("""
            INSERT INTO acs_table (acs_table_id, title, topic, table_type, description)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (acs_table_id) DO UPDATE SET
                title = EXCLUDED.title,
                topic = EXCLUDED.topic,
                table_type = EXCLUDED.table_type,
                description = EXCLUDED.description
        """, (
            table_code,
            metadata["title"],
            metadata["topic"],
            metadata["table_type"],
            metadata["description"]
        ))

    def _ingest_variables_and_values(
        self,
        df: pd.DataFrame,
        table_code: str,
        year: int
    ):
        """
        Ingest ACS variables and values from a DataFrame.

        Args:
            df: DataFrame with census data
            table_code: ACS table code
            year: Survey year
        """
        # Geography columns that should not be treated as variables
        geo_columns = {'state', 'county', 'tract', 'NAME'}

        # Get all columns that are variables (not geography)
        variable_columns = [col for col in df.columns if col not in geo_columns]

        self.logger.info(f"Found {len(variable_columns)} variables in {table_code}")

        # Bulk insert variables and get their integer IDs
        # Create mapping from (acs_table_id, name) to integer id
        variable_key_to_int_id = {}
        
        if variable_columns:
            variable_data = [
                (table_code, var_col)
                for var_col in variable_columns
            ]
            
            self.db.connect()
            with self.db.conn.cursor() as cur:
                # Use COPY for bulk insert (faster than INSERT)
                # Create temporary table for upsert logic
                cur.execute("""
                    CREATE TEMP TABLE temp_acs_variable (
                        acs_table_id VARCHAR(100),
                        name TEXT
                    ) ON COMMIT DROP
                """)
                
                # Use COPY to load into temp table
                buffer = StringIO()
                for row in variable_data:
                    buffer.write('\t'.join(str(x) for x in row) + '\n')
                buffer.seek(0)
                
                cur.copy_from(
                    buffer,
                    'temp_acs_variable',
                    columns=('acs_table_id', 'name'),
                    null=''
                )
                
                # Upsert from temp table and return IDs
                cur.execute("""
                    INSERT INTO acs_variable (acs_table_id, name)
                    SELECT acs_table_id, name
                    FROM temp_acs_variable
                    ON CONFLICT (acs_table_id, name) DO UPDATE SET
                        name = EXCLUDED.name
                    RETURNING id, acs_table_id, name
                """)
                
                # Build mapping from (acs_table_id, name) to integer id
                for row in cur.fetchall():
                    int_id, acs_table_id, name = row
                    variable_key_to_int_id[(acs_table_id, name)] = int_id
            self.db.conn.commit()

        # Construct geoid from geography columns
        # For state-level data
        if 'state' in df.columns and 'county' not in df.columns:
            df['geoid'] = df['state'].astype(str).str.zfill(2)
        # For county-level data
        elif 'state' in df.columns and 'county' in df.columns and 'tract' not in df.columns:
            df['geoid'] = (
                df['state'].astype(str).str.zfill(2) +
                df['county'].astype(str).str.zfill(3)
            )
        # For tract-level data
        elif 'state' in df.columns and 'county' in df.columns and 'tract' in df.columns:
            df['geoid'] = (
                df['state'].astype(str).str.zfill(2) +
                df['county'].astype(str).str.zfill(3) +
                df['tract'].astype(str).str.zfill(6)
            )
        else:
            self.logger.warning("Could not construct geoid from available columns")
            return

        # Prepare values for bulk insertion using integer variable IDs
        value_data = []
        
        for idx, row in df.iterrows():
            geoid = row['geoid']
            
            # Collect values for all variables
            for var_col in variable_columns:
                try:
                    value = row[var_col]

                    # Skip null/empty values
                    if pd.isna(value) or value == '':
                        continue

                    # Convert to float
                    try:
                        value_float = float(value)
                    except (ValueError, TypeError):
                        continue

                    # Get integer ID from mapping using (acs_table_id, name)
                    variable_key = (table_code, var_col)
                    variable_int_id = variable_key_to_int_id.get(variable_key)
                    if variable_int_id is None:
                        self.logger.warning(f"Variable not found in mapping: {table_code}.{var_col}")
                        continue
                    
                    value_data.append((geoid, variable_int_id, year, value_float))

                except Exception as e:
                    self.logger.warning(f"Failed to prepare value for {var_col}: {e}")
                    continue

        # Stop if no data to insert
        if not value_data:
            self.logger.warning(f"No values to insert for {table_code}")
            return

        # Set batch size to minimum of 10000 or total data length
        batch_size = min(10000, len(value_data))

        # Bulk insert values using COPY (optimized for large data loads)
        # Reference: https://www.postgresql.org/docs/current/populate.html
        inserted_count = 0
        self.db.connect()
        
        # Use COPY for bulk insert (much faster than INSERT)
        # Process in batches to avoid memory issues with very large datasets
        for i in range(0, len(value_data), batch_size):
            batch = value_data[i:i + batch_size]
            
            try:
                with self.db.conn.cursor() as cur:
                    # Use COPY for bulk insert (faster than execute_values)
                    buffer = StringIO()
                    for row in batch:
                        # Format: geoid, variable_id, year, value
                        buffer.write('\t'.join(str(x) for x in row) + '\n')
                    buffer.seek(0)
                    
                    cur.copy_from(
                        buffer,
                        'acs_value',
                        columns=('geoid', 'variable_id', 'year', 'value'),
                        null=''
                    )
                
                self.db.conn.commit()
                inserted_count += len(batch)
                self.logger.info(f"  → Inserted {inserted_count}/{len(value_data)} values...")
            except Exception as e:
                self.db.conn.rollback()
                self.logger.warning(f"Failed to insert batch: {e}")
                # Fallback to execute_values for problematic batches
                try:
                    with self.db.conn.cursor() as cur:
                        execute_values(
                            cur,
                            """
                            INSERT INTO acs_value (geoid, variable_id, year, value)
                            VALUES %s
                            """,
                            batch,
                            page_size=1000
                        )
                    self.db.conn.commit()
                    inserted_count += len(batch)
                except Exception as fallback_error:
                    self.db.conn.rollback()
                    self.logger.warning(f"Fallback insert also failed: {fallback_error}")
                    # Try inserting batch one by one to identify problematic rows
                    for row_data in batch:
                        try:
                            with self.db.conn.cursor() as cur:
                                cur.execute(
                                    """
                                    INSERT INTO acs_value (geoid, variable_id, year, value)
                                    VALUES (%s, %s, %s, %s)
                                    """,
                                    row_data
                                )
                            self.db.conn.commit()
                            inserted_count += 1
                        except Exception as row_error:
                            self.db.conn.rollback()
                            self.logger.warning(f"Failed to insert row {row_data}: {row_error}")
                            continue

        self.logger.info(f"Inserted {inserted_count} total values for {table_code}")

    def _process_csv_file(
        self,
        csv_path: Path,
        table_code: str,
        year: int,
        state: str
    ):
        """
        Process a single CSV file and ingest into database.

        Args:
            csv_path: Path to CSV file
            table_code: ACS table code
            year: Survey year
            state: State abbreviation
        """
        self.logger.info(f"Processing {csv_path.name}...")

        # Read CSV
        df = pd.read_csv(csv_path)
        self.logger.info(f"  Loaded {len(df)} rows, {len(df.columns)} columns")

        # Ingest table metadata
        self._ingest_acs_table(table_code)

        # Ingest variables and values
        self._ingest_variables_and_values(df, table_code, year)

    def _drop_indexes_and_constraints(self):
        """Drop indexes and foreign key constraints for faster bulk loading."""
        self.logger.info("Dropping indexes and foreign key constraints for bulk loading...")
        self.db.connect()
        
        with self.db.conn.cursor() as cur:
            # Drop indexes on acs_value table
            cur.execute("DROP INDEX IF EXISTS idx_acs_value_geoid")
            cur.execute("DROP INDEX IF EXISTS idx_acs_value_variable")
            cur.execute("DROP INDEX IF EXISTS idx_acs_value_year")
            
            # Drop foreign key constraints on acs_value table
            # Find and drop FK constraints
            cur.execute("""
                SELECT conname
                FROM pg_constraint
                WHERE conrelid = 'acs_value'::regclass
                AND contype = 'f'
            """)
            fk_constraints = cur.fetchall()
            for (conname,) in fk_constraints:
                cur.execute(f"ALTER TABLE acs_value DROP CONSTRAINT IF EXISTS {conname}")
            
        self.db.conn.commit()
        self.logger.info("Indexes and constraints dropped")

    def _recreate_indexes_and_constraints(self):
        """Recreate indexes and foreign key constraints after bulk loading."""
        self.logger.info("Recreating indexes and foreign key constraints...")
        self.db.connect()
        
        with self.db.conn.cursor() as cur:
            # Recreate indexes (faster to create on existing data than update incrementally)
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_acs_value_geoid ON acs_value(geoid)
            """)
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_acs_value_variable ON acs_value(variable_id)
            """)
            cur.execute("""
                CREATE INDEX IF NOT EXISTS idx_acs_value_year ON acs_value(year)
            """)
            
            # Recreate foreign key constraints
            # Note: This validates all existing data, which may take time
            cur.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'acs_value_geoid_fkey'
                    ) THEN
                        ALTER TABLE acs_value
                        ADD CONSTRAINT acs_value_geoid_fkey
                        FOREIGN KEY (geoid) REFERENCES census_tracts(geoid);
                    END IF;
                END $$;
            """)
            
            cur.execute("""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'acs_value_variable_id_fkey'
                    ) THEN
                        ALTER TABLE acs_value
                        ADD CONSTRAINT acs_value_variable_id_fkey
                        FOREIGN KEY (variable_id) REFERENCES acs_variable(id);
                    END IF;
                END $$;
            """)
            
        self.db.conn.commit()
        self.logger.info("Indexes and constraints recreated")

    def _run_analyze(self):
        """Run ANALYZE to update table statistics after bulk loading."""
        self.logger.info("Running ANALYZE to update table statistics...")
        self.db.connect()
        
        with self.db.conn.cursor() as cur:
            cur.execute("ANALYZE acs_value")
            cur.execute("ANALYZE acs_variable")
            cur.execute("ANALYZE acs_table")
        
        self.db.conn.commit()
        self.logger.info("ANALYZE completed")

    def process(self, test_mode: bool = False):
        """
        Main processing function to download CSV files from GCS and ingest into database.
        
        Optimized for bulk loading following PostgreSQL best practices:
        - Drops indexes and FK constraints before loading
        - Uses COPY for bulk inserts (faster than INSERT)
        - Recreates indexes and FK constraints after loading
        - Runs ANALYZE to update statistics
        
        Reference: https://www.postgresql.org/docs/current/populate.html

        Args:
            test_mode: If True, only process first few files for testing
        """
        self.logger.info(f"Starting census data ingestion for {self.city}")

        # Optimize for bulk loading: drop indexes and constraints
        # Reference: https://www.postgresql.org/docs/current/populate.html#POPULATE-RM-INDEXES
        self._drop_indexes_and_constraints()

        # Download CSV files from GCS
        download_dir = Path(self.download_directory())
        download_dir.mkdir(parents=True, exist_ok=True)

        self.logger.info(f"Downloading files from GCS to {download_dir}")
        gcs_path = self.gcp_storage_markdown_directory()

        # Download all CSV files
        self.storage.download_dir(gcs_path, str(download_dir))

        # Find manifest file
        manifest_path = download_dir / "manifest.csv"

        if not manifest_path.exists():
            self.logger.error(f"Manifest file not found at {manifest_path}")
            # Try to process CSV files directly
            csv_files = list(download_dir.glob("*.csv"))
            csv_files = [f for f in csv_files if f.name != "manifest.csv"]

            if not csv_files:
                self.logger.error("No CSV files found to process")
                return

            self.logger.info(f"Found {len(csv_files)} CSV files without manifest")

            # Process each CSV file
            for i, csv_file in enumerate(csv_files):
                if test_mode and i > 2:
                    self.logger.info("Test mode: stopping after 2 files")
                    break

                # Parse filename: {city}_{state}_{table_code}_{year}.csv
                parts = csv_file.stem.split('_')
                if len(parts) >= 4:
                    city = parts[0]
                    state = parts[1]
                    table_code = parts[2]
                    year = int(parts[3])

                    self._process_csv_file(csv_file, table_code, year, state)
        else:
            # Read manifest
            manifest_df = pd.read_csv(manifest_path)
            self.logger.info(f"Found {len(manifest_df)} files in manifest")

            # Process each file in manifest
            for idx, row in manifest_df.iterrows():
                if test_mode and idx > 2:
                    self.logger.info("Test mode: stopping after 2 files")
                    break

                city = row['city']
                state = row['state']
                table_code = row['table']
                year = int(row['year'])

                # Construct CSV filename
                csv_filename = f"{city}_{state}_{table_code}_{year}.csv"
                csv_path = download_dir / csv_filename

                if not csv_path.exists():
                    self.logger.warning(f"CSV file not found: {csv_filename}")
                    continue

                self._process_csv_file(csv_path, table_code, year, state)

        # Recreate indexes and constraints after bulk loading
        # Reference: https://www.postgresql.org/docs/current/populate.html#POPULATE-RM-INDEXES
        self._recreate_indexes_and_constraints()
        
        # Run ANALYZE to update statistics for query planner
        # Reference: https://www.postgresql.org/docs/current/populate.html#POPULATE-ANALYZE
        self._run_analyze()

        self.logger.info(f"Census data ingestion completed for {self.city}")
