"""
Census Processor for ingesting ACS data into the database.

This processor reads CSV files generated by the Census Collector and inserts
data into the following tables:
- CENSUS_TRACT: Geographic tracts
- ACS_TABLE: ACS table definitions
- ACS_RELEASE: ACS release information (year, dataset, vintage)
- ACS_VARIABLE: ACS variable definitions
- ACS_VALUE: Actual census values
"""

import os
import logging
import pandas as pd
from pathlib import Path
from typing import Dict, List, Optional
from utils.db_accessor import DBAccessor
from utils.gcp_storage import GCPStorage
from template import BaseProcessor


class CensusProcessor(BaseProcessor):
    """Process census CSV files and ingest into database."""

    def __init__(self, city: str):
        super().__init__()
        self.city = city
        self._init_logger()
        self._init_db()
        self._init_storage()

    def _init_logger(self):
        """Initialize logger."""
        self.logger = logging.getLogger(f"{self.__class__.__name__}")
        if not self.logger.hasHandlers():
            handler = logging.StreamHandler()
            formatter = logging.Formatter("%(asctime)s %(levelname)s: %(message)s")
            handler.setFormatter(formatter)
            self.logger.addHandler(handler)
            self.logger.setLevel(logging.INFO)

    def _init_db(self):
        """Initialize database connection and create tables."""
        self.db_name = os.environ.get("APP_DB_NAME")
        self.db = DBAccessor(db_name=self.db_name)
        self._create_census_tables()

    def _init_storage(self):
        """Initialize GCP Storage client."""
        self.gcp_project = os.environ.get("GCP_PROJECT")
        self.gcp_bucket = os.environ.get("GCS_BUCKET_NAME")
        credentials_path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS")
        self.storage = GCPStorage(
            gcp_project=self.gcp_project,
            bucket_name=self.gcp_bucket,
            credentials_path=credentials_path
        )

    def download_directory(self) -> str:
        """Return the download directory path for this processor."""
        return os.path.abspath(f"tmp/census/{self.city}")

    def gcp_storage_markdown_directory(self) -> str:
        """Return the GCS storage path for census CSV files."""
        return f"census/{self.city}"

    def _create_census_tables(self):
        """Create all census-related tables in the database."""
        self.logger.info("Creating census tables...")

        # Create CENSUS_TRACT table
        self.db.execute("""
            CREATE TABLE IF NOT EXISTS census_tract (
                geoid VARCHAR(50) PRIMARY KEY,
                geom GEOMETRY(MultiPolygon, 4326),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS idx_census_tract_geom ON census_tract USING GIST(geom);
        """)

        # Create ACS_TABLE table
        self.db.execute("""
            CREATE TABLE IF NOT EXISTS acs_table (
                acs_table_id VARCHAR(100) PRIMARY KEY,
                title TEXT,
                topic VARCHAR(500),
                table_type VARCHAR(200),
                description TEXT
            );
        """)

        # Create ACS_RELEASE table
        self.db.execute("""
            CREATE TABLE IF NOT EXISTS acs_release (
                acs_release_id VARCHAR(500) PRIMARY KEY,
                acs_table_id VARCHAR(100) REFERENCES acs_table(acs_table_id),
                year INTEGER NOT NULL,
                dataset VARCHAR(500),
                vintage VARCHAR(100)
            );
            CREATE INDEX IF NOT EXISTS idx_acs_release_table ON acs_release(acs_table_id);
            CREATE INDEX IF NOT EXISTS idx_acs_release_year ON acs_release(year);
        """)

        # Create ACS_VARIABLE table
        self.db.execute("""
            CREATE TABLE IF NOT EXISTS acs_variable (
                variable_id VARCHAR(500) PRIMARY KEY,
                acs_table_id VARCHAR(100) REFERENCES acs_table(acs_table_id),
                name TEXT,
                concept TEXT
            );
            CREATE INDEX IF NOT EXISTS idx_acs_variable_table ON acs_variable(acs_table_id);
        """)

        # Create ACS_VALUE table
        self.db.execute("""
            CREATE TABLE IF NOT EXISTS acs_value (
                acs_value_id SERIAL PRIMARY KEY,
                geoid VARCHAR(50) REFERENCES census_tract(geoid),
                acs_release_id VARCHAR(500) REFERENCES acs_release(acs_release_id),
                variable_id VARCHAR(500) REFERENCES acs_variable(variable_id),
                value FLOAT,
                ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
            CREATE INDEX IF NOT EXISTS idx_acs_value_geoid ON acs_value(geoid);
            CREATE INDEX IF NOT EXISTS idx_acs_value_release ON acs_value(acs_release_id);
            CREATE INDEX IF NOT EXISTS idx_acs_value_variable ON acs_value(variable_id);
        """)

        self.logger.info("Census tables created successfully")

    def _get_table_metadata(self, table_code: str) -> Dict:
        """
        Get metadata for an ACS table.

        Args:
            table_code: ACS table code (e.g., "DP04", "S1901")

        Returns:
            Dictionary with table metadata
        """
        # Map table codes to metadata
        # This is a simplified mapping - in production, you might fetch this from Census API
        table_metadata = {
            "DP02": {
                "title": "Selected Social Characteristics",
                "topic": "Social",
                "table_type": "Data Profile",
                "description": "Social characteristics including household types, education, and language"
            },
            "DP04": {
                "title": "Selected Housing Characteristics",
                "topic": "Housing",
                "table_type": "Data Profile",
                "description": "Housing characteristics including rent, tenure, and vacancy"
            },
            "DP05": {
                "title": "Demographic and Housing Estimates",
                "topic": "Demographics",
                "table_type": "Data Profile",
                "description": "Population by age, race, and sex"
            },
            "S0701": {
                "title": "Geographic Mobility",
                "topic": "Mobility",
                "table_type": "Subject Table",
                "description": "Migration patterns and geographic mobility"
            },
            "S0801": {
                "title": "Commuting Characteristics",
                "topic": "Transportation",
                "table_type": "Subject Table",
                "description": "Commute to work patterns"
            },
            "S0802": {
                "title": "Means of Transportation to Work",
                "topic": "Transportation",
                "table_type": "Subject Table",
                "description": "Vehicle availability and transportation modes"
            },
            "S0804": {
                "title": "Means of Transportation to Work by Selected Characteristics",
                "topic": "Transportation",
                "table_type": "Subject Table",
                "description": "Detailed transportation mode characteristics"
            },
            "S1101": {
                "title": "Households and Families",
                "topic": "Households",
                "table_type": "Subject Table",
                "description": "Household size and composition"
            },
            "S1501": {
                "title": "Educational Attainment",
                "topic": "Education",
                "table_type": "Subject Table",
                "description": "Education levels by demographics"
            },
            "S1701": {
                "title": "Poverty Status",
                "topic": "Income",
                "table_type": "Subject Table",
                "description": "Poverty rates and thresholds"
            },
            "S1901": {
                "title": "Income in the Past 12 Months",
                "topic": "Income",
                "table_type": "Subject Table",
                "description": "Household income distribution"
            },
            "S1903": {
                "title": "Median Income",
                "topic": "Income",
                "table_type": "Subject Table",
                "description": "Median income by demographics"
            },
            "S2201": {
                "title": "Food Stamps/SNAP",
                "topic": "Assistance",
                "table_type": "Subject Table",
                "description": "Food stamp and SNAP participation"
            },
            "S2301": {
                "title": "Employment Status",
                "topic": "Employment",
                "table_type": "Subject Table",
                "description": "Labor force participation and unemployment"
            },
            "S2403": {
                "title": "Industry by Sex",
                "topic": "Employment",
                "table_type": "Subject Table",
                "description": "Industry distribution by sex"
            },
            "S2404": {
                "title": "Industry by Sex for Full-Time Workers",
                "topic": "Employment",
                "table_type": "Subject Table",
                "description": "Full-time employment by industry"
            },
            "S2501": {
                "title": "Occupancy Characteristics",
                "topic": "Housing",
                "table_type": "Subject Table",
                "description": "Tenure and occupancy details"
            },
            "S2503": {
                "title": "Financial Characteristics",
                "topic": "Housing",
                "table_type": "Subject Table",
                "description": "Housing cost burden and mortgage status"
            },
        }

        return table_metadata.get(table_code, {
            "title": f"ACS Table {table_code}",
            "topic": "Unknown",
            "table_type": "Unknown",
            "description": f"American Community Survey Table {table_code}"
        })

    def _ingest_acs_table(self, table_code: str):
        """
        Insert or update ACS table metadata.

        Args:
            table_code: ACS table code
        """
        metadata = self._get_table_metadata(table_code)

        self.db.execute("""
            INSERT INTO acs_table (acs_table_id, title, topic, table_type, description)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (acs_table_id) DO UPDATE SET
                title = EXCLUDED.title,
                topic = EXCLUDED.topic,
                table_type = EXCLUDED.table_type,
                description = EXCLUDED.description
        """, (
            table_code,
            metadata["title"],
            metadata["topic"],
            metadata["table_type"],
            metadata["description"]
        ))

    def _ingest_acs_release(self, table_code: str, year: int, dataset: str):
        """
        Insert or update ACS release information.

        Args:
            table_code: ACS table code
            year: Survey year
            dataset: Dataset name (e.g., "acs/acs5/profile")
        """
        release_id = f"{table_code}_{year}_{dataset.replace('/', '_')}"
        vintage = str(year)  # Vintage is typically the end year of the 5-year period

        self.db.execute("""
            INSERT INTO acs_release (acs_release_id, acs_table_id, year, dataset, vintage)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (acs_release_id) DO UPDATE SET
                year = EXCLUDED.year,
                dataset = EXCLUDED.dataset,
                vintage = EXCLUDED.vintage
        """, (release_id, table_code, year, dataset, vintage))

        return release_id

    def _ingest_census_tract(self, geoid: str):
        """
        Insert census tract if it doesn't exist.

        Args:
            geoid: Geographic identifier
        """
        self.db.execute("""
            INSERT INTO census_tract (geoid)
            VALUES (%s)
            ON CONFLICT (geoid) DO NOTHING
        """, (geoid,))

    def _ingest_variables_and_values(
        self,
        df: pd.DataFrame,
        release_id: str,
        table_code: str
    ):
        """
        Ingest ACS variables and values from a DataFrame.

        Args:
            df: DataFrame with census data
            release_id: ACS release identifier
            table_code: ACS table code
        """
        # Geography columns that should not be treated as variables
        geo_columns = {'state', 'county', 'tract', 'NAME'}

        # Get all columns that are variables (not geography)
        variable_columns = [col for col in df.columns if col not in geo_columns]

        self.logger.info(f"Found {len(variable_columns)} variables in {table_code}")

        # Insert variables
        for var_col in variable_columns:
            variable_id = f"{table_code}_{var_col}"

            self.db.execute("""
                INSERT INTO acs_variable (variable_id, acs_table_id, name, concept)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (variable_id) DO UPDATE SET
                    name = EXCLUDED.name,
                    concept = EXCLUDED.concept
            """, (
                variable_id,
                table_code,
                var_col,
                f"{table_code} - {var_col}"  # Simplified concept
            ))

        # Construct geoid from geography columns
        # For state-level data
        if 'state' in df.columns and 'county' not in df.columns:
            df['geoid'] = df['state'].astype(str).str.zfill(2)
        # For county-level data
        elif 'state' in df.columns and 'county' in df.columns and 'tract' not in df.columns:
            df['geoid'] = (
                df['state'].astype(str).str.zfill(2) +
                df['county'].astype(str).str.zfill(3)
            )
        # For tract-level data
        elif 'state' in df.columns and 'county' in df.columns and 'tract' in df.columns:
            df['geoid'] = (
                df['state'].astype(str).str.zfill(2) +
                df['county'].astype(str).str.zfill(3) +
                df['tract'].astype(str).str.zfill(6)
            )
        else:
            self.logger.warning("Could not construct geoid from available columns")
            return

        # Insert census tracts and values
        inserted_count = 0
        batch_size = 100

        for idx, row in df.iterrows():
            geoid = row['geoid']

            # Insert tract
            self._ingest_census_tract(geoid)

            # Insert values for all variables
            for var_col in variable_columns:
                try:
                    value = row[var_col]

                    # Skip null/empty values
                    if pd.isna(value) or value == '':
                        continue

                    # Convert to float
                    try:
                        value_float = float(value)
                    except (ValueError, TypeError):
                        continue

                    variable_id = f"{table_code}_{var_col}"

                    self.db.execute("""
                        INSERT INTO acs_value (geoid, acs_release_id, variable_id, value)
                        VALUES (%s, %s, %s, %s)
                    """, (geoid, release_id, variable_id, value_float))

                    inserted_count += 1

                    # Commit in batches
                    if inserted_count % batch_size == 0:
                        self.db.conn.commit()
                        self.logger.info(f"  → Inserted {inserted_count} values...")

                except Exception as e:
                    self.logger.warning(f"Failed to insert value for {var_col}: {e}")
                    continue

        # Final commit
        self.db.conn.commit()
        self.logger.info(f"Inserted {inserted_count} total values for {table_code}")

    def _process_csv_file(
        self,
        csv_path: Path,
        table_code: str,
        year: int,
        state: str
    ):
        """
        Process a single CSV file and ingest into database.

        Args:
            csv_path: Path to CSV file
            table_code: ACS table code
            year: Survey year
            state: State abbreviation
        """
        self.logger.info(f"Processing {csv_path.name}...")

        # Read CSV
        df = pd.read_csv(csv_path)
        self.logger.info(f"  Loaded {len(df)} rows, {len(df.columns)} columns")

        # Determine dataset from table code prefix
        if table_code.startswith('DP'):
            dataset = 'acs/acs5/profile'
        elif table_code.startswith('S'):
            dataset = 'acs/acs5/subject'
        else:
            dataset = 'acs/acs5'

        # Ingest table metadata
        self._ingest_acs_table(table_code)

        # Ingest release information
        release_id = self._ingest_acs_release(table_code, year, dataset)

        # Ingest variables and values
        self._ingest_variables_and_values(df, release_id, table_code)

    def process(self, test_mode: bool = False):
        """
        Main processing function to download CSV files from GCS and ingest into database.

        Args:
            test_mode: If True, only process first few files for testing
        """
        self.logger.info(f"Starting census data ingestion for {self.city}")

        # Download CSV files from GCS
        download_dir = Path(self.download_directory())
        download_dir.mkdir(parents=True, exist_ok=True)

        self.logger.info(f"Downloading files from GCS to {download_dir}")
        gcs_path = self.gcp_storage_markdown_directory()

        # Download all CSV files
        self.storage.download_dir(gcs_path, str(download_dir))

        # Find manifest file
        manifest_path = download_dir / "manifest.csv"

        if not manifest_path.exists():
            self.logger.error(f"Manifest file not found at {manifest_path}")
            # Try to process CSV files directly
            csv_files = list(download_dir.glob("*.csv"))
            csv_files = [f for f in csv_files if f.name != "manifest.csv"]

            if not csv_files:
                self.logger.error("No CSV files found to process")
                return

            self.logger.info(f"Found {len(csv_files)} CSV files without manifest")

            # Process each CSV file
            for i, csv_file in enumerate(csv_files):
                if test_mode and i >= 3:
                    self.logger.info("Test mode: stopping after 3 files")
                    break

                # Parse filename: {city}_{state}_{table_code}_{year}.csv
                parts = csv_file.stem.split('_')
                if len(parts) >= 4:
                    city = parts[0]
                    state = parts[1]
                    table_code = parts[2]
                    year = int(parts[3])

                    self._process_csv_file(csv_file, table_code, year, state)
        else:
            # Read manifest
            manifest_df = pd.read_csv(manifest_path)
            self.logger.info(f"Found {len(manifest_df)} files in manifest")

            # Process each file in manifest
            for idx, row in manifest_df.iterrows():
                if test_mode and idx >= 3:
                    self.logger.info("Test mode: stopping after 3 files")
                    break

                city = row['city']
                state = row['state']
                table_code = row['table']
                year = int(row['year'])

                # Construct CSV filename
                csv_filename = f"{city}_{state}_{table_code}_{year}.csv"
                csv_path = download_dir / csv_filename

                if not csv_path.exists():
                    self.logger.warning(f"CSV file not found: {csv_filename}")
                    continue

                self._process_csv_file(csv_path, table_code, year, state)

        self.logger.info(f"Census data ingestion completed for {self.city}")
