[project]
name = "ner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.2.0",
    "accelerate>=0.25.0,<1.0.0",
    "datasets>=2.14.0,<3.0.0",
    "ipykernel>=7.0.1",
    "seqeval>=1.2.2",
    "transformers>=4.36.0,<4.40.0",
    "google-cloud-storage>=2.19.0",
    "wandb==0.15.11",
    "tqdm>=4.66.0",
    "dotenv>=0.9.9",
    "numpy<2.0",
]
