from utils.gcp_storage import GCPStorage
from .base import DevelopmentPlansBaseProcessor
import os
import json
import pandas as pd


class NerJsonProcessor(DevelopmentPlansBaseProcessor):
    """
    NER JSON processor for embedding development plans documents.
    Processes .ner.json files that have been generated by the NER pipeline.
    """

    def __init__(
        self,
        city: str,
        storage: GCPStorage,
        gcp_project: str,
        gcp_region: str,
        gcp_storage_source_directory: str,
    ):
        super().__init__(city, gcp_project, gcp_region, gcp_storage_source_directory)
        self.logger.info(
            f"Initialized {self.__class__.__name__} processor for {self.city}"
        )
        self.storage = storage
        self.gcp_project = gcp_project
        self.gcp_region = gcp_region

    def load_ner_json_files_from_gcp(self, test_mode: bool = False):
        """
        Load all .ner.json files from GCS bucket.
        Structure: development_plans/{city}/{project}/*.ner.json

        Returns:
            List of tuples: (blob, project_name)
        """
        # List all blobs in the development_plans directory
        blobs = self.storage.list_blobs(prefix=f"{self.gcp_storage_source_directory}")

        # Filter for .ner.json files (excluding metadata.json)
        ner_json_blobs = []
        for blob in blobs:
            if blob.name.endswith(".ner.json") and not blob.name.endswith("metadata.json"):
                # Extract project name from path
                # Path format: development_plans/{city}/{project}/{file}.ner.json
                path_parts = blob.name.split("/")
                if len(path_parts) >= 3:
                    project_name = path_parts[-2]  # Second to last part is project name
                    ner_json_blobs.append((blob, project_name))

        if len(ner_json_blobs) == 0:
            raise ValueError(
                f"No .ner.json files found for {self.city}. Please run the NER pipeline first."
            )

        if test_mode:
            ner_json_blobs = ner_json_blobs[:3]  # Process a few files in test mode

        return ner_json_blobs

    def process_single_ner_json_file(self, json_blob, project_name):
        """
        Process a single .ner.json file: download it, extract text and metadata.

        Args:
            json_blob: GCS blob object for the .ner.json file
            project_name: Name of the project (directory name, used as fallback)

        Returns:
            tuple: (text_content, project_name_from_data, file_name, metadata, source_gcs_path)
        """
        # Ensure download directory exists
        os.makedirs(self.download_directory(), exist_ok=True)

        # Download the JSON file to a temp location
        temp_path = f"{self.download_directory()}/{os.path.basename(json_blob.name)}"
        self.storage.download_blob_to_file(json_blob.name, temp_path)

        # Load the JSON file
        with open(temp_path, "r", encoding="utf-8") as f:
            json_data = json.load(f)

        # Extract the "data" and "meta" sections
        data_section = json_data.get("data", {})
        meta_section = json_data.get("meta", {})

        # Extract text from the "data.text" key
        text_content = data_section.get("text", "")

        if not text_content:
            self.logger.warning(f"No text found in {json_blob.name}")
            return None, None, None, None

        # Use metadata from the "meta" section
        metadata = meta_section

        # Extract project_name and file_name from the data section
        # These are already parsed from the PDF filename
        project_name_from_data = data_section.get("project_name", project_name)
        file_name = data_section.get("file_name", "")

        # If file_name still has .pdf extension, remove it
        if file_name.endswith(".pdf"):
            file_name = file_name.replace(".pdf", "")

        return text_content, project_name_from_data, file_name, metadata, json_blob.name

    def create_chunk_data(
        self,
        all_chunk_data: list,
        text_content: str,
        project_name: str,
        file_name: str,
        metadata: dict,
        source_gcs_path: str,
    ):
        """
        Create chunks from text content.

        Args:
            all_chunk_data: List to append chunk data to
            text_content: The text content to chunk
            project_name: Name of the project
            file_name: Name of the file (without .ner.json)
            metadata: Metadata from the "meta" key
            source_gcs_path: GCS path to the original .ner.json file
        """
        chunks = self.text_splitter.create_documents([text_content])
        chunk_texts = [doc.page_content for doc in chunks]

        # Add GCS information to metadata
        bucket_name = self.storage.bucket.name
        enhanced_metadata = {
            **metadata,  # Include original metadata from the "meta" key
            "source_ner_json_gcs_path": source_gcs_path,
            "bucket_name": bucket_name,
            "source_ner_json_url": f"gs://{bucket_name}/{source_gcs_path}",
        }

        for chunk_text in chunk_texts:
            chunk_data = {
                "text_chunk": chunk_text,
                "project_name": project_name,
                "file_name": file_name,
                "zoning_codes": [],  # Empty for now - NER model not integrated
                "article_reference": [],  # Empty for now - NER model not integrated
                "location_context": "",  # Empty for now - NER model not integrated
                "metadata": enhanced_metadata,
            }
            all_chunk_data.append(chunk_data)

        if not chunk_texts:
            self.logger.warning(f"No chunks created for {project_name}/{file_name}")

    def generate_embedding_table(self, all_chunk_data: list):
        """
        Generate embeddings for all chunks and create a dataframe.

        Args:
            all_chunk_data: List of chunk dictionaries

        Returns:
            DataFrame with chunks and their embeddings
        """
        data_df = pd.DataFrame(all_chunk_data)
        chunks = data_df["text_chunk"].values.tolist()
        embeddings = self._generate_text_embeddings(chunks, batch_size=15)
        data_df["embedding"] = embeddings
        return data_df

    def process(self, test_mode: bool = False):
        """
        Main processing method: loads .ner.json files from GCS, extracts text and metadata,
        creates chunks, generates embeddings, and uploads results.

        Args:
            test_mode: If True, only process the first few files for testing
        """
        self.logger.info(
            f"Starting {self.__class__.__name__} processor (test_mode={test_mode})"
        )
        ner_json_blobs = self.load_ner_json_files_from_gcp(test_mode=test_mode)
        total_files = len(ner_json_blobs)
        self.logger.info(f"Found {total_files} .ner.json file(s) to process")
        all_chunk_data = []

        for idx, (json_blob, project_name) in enumerate(ner_json_blobs, 1):
            self.logger.info(f"\n[{idx}/{total_files}] Processing: {json_blob.name}")
            result = self.process_single_ner_json_file(json_blob, project_name)

            # Skip if no text was found
            if result[0] is None:
                self.logger.warning(f"[{idx}/{total_files}] Skipping - no text content")
                continue

            text_content, project_name_from_data, file_name, metadata, source_gcs_path = result

            self.create_chunk_data(
                all_chunk_data,
                text_content,
                project_name_from_data,
                file_name,
                metadata,
                source_gcs_path,
            )
            self.logger.info(
                f"[{idx}/{total_files}] Created {len(all_chunk_data)} chunks so far"
            )

        if not all_chunk_data:
            self.logger.error("No chunks were created. Exiting.")
            return

        # Generate embeddings
        self.logger.info(f"\nGenerating embeddings for {len(all_chunk_data)} chunks...")
        data_df = self.generate_embedding_table(all_chunk_data)
        self.logger.info(f"✓ Generated {len(data_df)} embeddings")

        # Save to JSONL in GCS
        jsonl_content = data_df.to_json(orient="records", lines=True)
        self.storage.upload_string_to_blob(
            jsonl_content, f"{self.gcp_storage_output_directory()}/embeddings.jsonl"
        )
        self.logger.info(
            f"Uploaded embeddings to: {self.gcp_storage_output_directory()}/embeddings.jsonl"
        )

        # Save internally as JSON for better readability
        data_df.to_json(
            os.path.join(self.download_directory(), "embeddings.json"),
            orient="records",
            indent=2,
        )

        # Save embeddings to PostgreSQL database
        # Convert dataframe back to list of dicts with embeddings
        embeddings_with_data = data_df.to_dict("records")
        self.logger.info("\nSaving embeddings to database...")
        inserted, skipped = self._insert_embeddings_to_db(embeddings_with_data)

        # Final summary
        self.logger.info("\n" + "=" * 60)
        self.logger.info("PROCESSING COMPLETE")
        self.logger.info("=" * 60)
        self.logger.info(f"Files processed:     {len([r for r in ner_json_blobs if self.process_single_ner_json_file(r[0], r[1])[0] is not None])}/{total_files}")
        self.logger.info(f"Chunks created:      {len(all_chunk_data)}")
        self.logger.info(f"Embeddings generated: {len(data_df)}")
        self.logger.info(f"Database records:    {inserted} inserted, {skipped} skipped")
        self.logger.info("=" * 60)
